// MongoDB Lab - ADBMS
// Introduction:
// • MongoDB is a NoSQL database that stores data in JSON-like documents (called BSON).
// • It is schema-less, which means each document can have a different structure.
// • It is used for handling large volumes of unstructured data.
// • Collections in MongoDB are like tables in SQL.
// • Documents in MongoDB are like rows in SQL, but more flexible.
// • It uses JavaScript-like syntax to query and manipulate data.

// MongoDB Basic Commands - ADBMS Lab

What is db?  -> It is a built-in variable in MongoDB shell. Always points to the current database selected using use.

| Data Type               | Example                                         | Description                         |
| ----------------------- | ----------------------------------------------- | ----------------------------------- |
| **String**              | `"name": "John"`                                | Text values                         |
| **Number (Int/Double)** | `"age": 25`                                     | Whole or decimal numbers            |
| **Boolean**             | `"isActive": true`                              | `true` or `false`                   |
| **Array**               | `"hobbies": ["reading", "sports"]`              | List of values                      |
| **Object**              | `"address": { "city": "Delhi", "zip": 123456 }` | Nested document                     |
| **Date**                | `"createdAt": new Date()`                       | Date and time value                 |
| **Null**                | `"middleName": null`                            | Represents missing or unknown value |
| **ObjectId**            | `"_id": ObjectId("...")`                        | Unique ID for every document        |


//✅ Difference Between {} and [] in MongoDB

| Symbol | Name                | Used For                   | Example                     |
| ------ | ------------------- | -------------------------- | --------------------------- |
| `{}`   | **Curly Braces**    | **Object / Document**      | `{ name: "John", age: 25 }` |
| `[]`   | **Square Brackets** | **Array / List of values** | `[ "reading", "cricket" ]`  |


// ===== MongoDB ADBMS Lab Commands =====

// 🔹 Show all databases
show dbs

// 🔹 Create or switch to a database
use myDatabase

// 🔹 Show current database
db

// 🔹 Create a new collection
db.createCollection("users")

// 🔹 Insert one document into users collection
db.users.insertOne({
  name: "John",
  age: 25,
  isActive: true,
  hobbies: ["reading", "cricket"],
  address: { city: "Delhi", zip: 110001 },
  createdAt: new Date(),
  middleName: null
})

// 🔹 Insert multiple documents
db.users.insertMany([
  { name: "Amit", age: 30, isActive: false },
  { name: "Sara", age: 22, isActive: true }
])

// 🔹 Find all documents in the collection
db.users.find()

// 🔹 Find with condition
db.users.find({ age: 25 })

// 🔹 Find and display output in readable format
db.users.find().pretty()

// 🔹 Find only one document (first match)
db.users.findOne({ isActive: true })

// 🔹 Drop the entire collection
db.users.drop()

// 🔹 Drop the current database
db.dropDatabase()

// ===== MongoDB Data Types Used in Example =====
// • String: "John"
// • Number: 25
// • Boolean: true / false
// • Array: ["reading", "cricket"]
// • Object: { city: "Delhi", zip: 110001 }
// • Date: new Date()
// • Null: null
// • ObjectId: Automatically generated by MongoDB for _id field

// 🔹 Sort by name in ascending order (A to Z)
db.users.find().sort({ name: 1 })

// 🔹 Sort by multiple fields: first by age descending, then name ascending
db.users.find().sort({ age: -1, name: 1 })

// 🔹 Use limit() with sort - Get the youngest person
db.users.find().sort({ age: 1 }).limit(1)

// 🔹 Use limit() with sort - Get the oldest person
db.users.find().sort({ age: -1 }).limit(1)



